steps:
- script: ls -l $(npm_config_change)

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CacheBeta@1
  inputs:
    key: $(CACHE_KEY)
    path: $(npm_config_change)
    cacheHitVar: CACHE_RESTORED 
  displayName: 'Cache npm'

- script: |
    npm ci
  displayName: 'npm ci'

- script: npm run-script build
  displayName: 'npm build'