# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CacheBeta@1
  inputs:
    key: npm4 | $(Agent.OS) | package-lock.json
    path: $(npm_config_cache)
    cacheHitVar: CACHE_RESTORED
  displayName: 'Cache npm'

- script: |
    npm ci
  displayName: 'npm ci'
  condition: ne(variables.CACHE_RESTORED, 'true')

- script: |
    ls -l $(Pipeline.Workspace)

- script: npm run-script build
  displayName: 'npm build'

- script: |
    ls -l $(Pipeline.Workspace)


