steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CacheBeta@1
  inputs:
    key: $(CACHE_KEY)
    path: $(NPM_CONFIG_PREFIX)
    cacheHitVar: CACHE_RESTORED 
  displayName: 'Cache npm'

- script: |
    npm ci
  displayName: 'npm ci'

- script: npm run-script build
  displayName: 'npm build'

#- script: ls -l $(NPM_CONFIG_CHANGE)