jobs:
- job:
  strategy:
    matrix:
      linux:    
        VM_IMAGE: ubuntu-16.04
      windows 2017:
        VM_IMAGE: vs2017-win2016
      macos 10.13:
        VM_IMAGE: macos-10.13
      macos 10.14:
        VM_IMAGE: macos-10.14
  pool:
    vmImage: $(VM_IMAGE)
  steps:
  - template: azure-pipelines-steps.yml