# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

#trigger:
#- master

#pool:
#  vmImage: 'ubuntu-latest'

stages:
- stage: firstrun
  displayName: 'Empty cache'
  jobs:
  - template: azure-pipelines-jobs.yml

- stage: secondrun
  dependsOn: firstrun
  displayName: 'Cached'
  jobs:
  - template: azure-pipelines-jobs.yml

variables:
  CACHE_PATH: $(Build.SourcesDirectory)/node_modules
  CACHE_KEY: npm | $(Agent.OS) | $(Build.BuildId) | package-lock.json
  CACHE_RESTOREKEYS: npm | $(Agent.OS) | $(Build.BuildId)

#steps:
#- task: NodeTool@0
#  inputs:
#    versionSpec: '10.x'
#  displayName: 'Install Node.js'
#
#- task: CacheBeta@1
#  inputs:
#    key: npmci | $(Agent.OS) | package-lock.json
#    path: $(npm_config_change)
#    cacheHitVar: CACHE_RESTORED 
#  displayName: 'Cache npm'
#
#- script: |
#    npm ci
#  displayName: 'npm ci'
#
#- script: npm run-script build
#  displayName: 'npm build'



