steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CacheBeta@1
  inputs:
    key: $(CACHE_KEY)
    path: $(CACHE_FOLDER)
    cacheHitVar: CACHE_RESTORED 
  displayName: 'Cache yarn packages'

- script: |
    yarn --frozen-lockfile
  displayName: 'Install dependencies'
  condition: and(ne(variables.CACHE_RESTORED, 'true'), ne(variables.SECOND_FILES, 'files'))

- script: yarn build
  displayName: 'npm build'
