steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CacheBeta@1
  inputs:
    key: $(CACHE_KEY)
    path: $(CACHE_PATH)
    restoreKeys: $(CACHE_RESTOREKEYS)
    cacheHitVar: CACHE_RESTORED 
  displayName: 'Cache npm'

- script: |
    npm install
  displayName: 'npm install'

- script: npm run-script build
  displayName: 'npm build'

#- script: ls -l $(NPM_CONFIG_CHANGE)